<Project>
  <ItemGroup>
    <PackageReference Include="Microsoft.Data.Sqlite.Core" Version="9.0.0" />
    <PackageReference Include="SQLitePCLRaw.bundle_e_sqlcipher" Version="2.1.10" />
    <PackageReference Include="System.Security.Cryptography.ProtectedData" Version="9.0.0" />
  </ItemGroup>
</Project>
